metrics: true
endpoints:
  - name: Docker Container Registry
    url: https://registry.brotherlogic-backend.com
    interval: 1m
    conditions:
      - "[STATUS] == 200"

  - name: Uptime Kuma
    url: https://uptime.brotherlogic.com
    interval: 1m
    conditions:
      - "[STATUS] == 200"
